[pytest]
markers = [
    "moss_args: customises the moss server with additional flags",
    "moss_https: adds https flags",
    "override_moss_port: override the default port, for debugging test cases",
    "no_tcp_check: don't open a socket to check if the server is live, just trust it's alive bro",
]